const XP_BASE_FACTOR = 0.5;
const XP_TANH_FACTOR = 7.5;
const LP_TANH_FACTOR = 1;

const BLOCK_TIME = 12;

const REWARDS_DEPLOYMENT_BLOCK = 21031003;
const VAULT_MANAGER_DEPLOYMENT_BLOCK = 20013820;
const DYAD_NFT_DEPLOYMENT_BLOCK = 17733160;
const KEROSENE_VAULT_DEPLOYMENT_BLOCK = 20055920;
const DYAD_XP_DEPLOYMENT_BLOCK = 20292049;

export {
  BLOCK_TIME,
  DYAD_NFT_DEPLOYMENT_BLOCK,
  DYAD_XP_DEPLOYMENT_BLOCK,
  KEROSENE_VAULT_DEPLOYMENT_BLOCK,
  LP_TANH_FACTOR,
  REWARDS_DEPLOYMENT_BLOCK,
  VAULT_MANAGER_DEPLOYMENT_BLOCK,
  XP_BASE_FACTOR,
  XP_TANH_FACTOR,
};
